# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/alfiebradic/vst3sdk/pluginterfaces/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.25.2/share/cmake/Modules/CheckSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.25.2/share/cmake/Modules/Internal/CheckSourceCompiles.cmake))

/Users/alfiebradic/Documents/basicDelay/build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.25.2/bin/cmake -H/Users/alfiebradic/Documents/basicDelay -B/Users/alfiebradic/Documents/basicDelay/build
